[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]


version = "0.8.23" 
evm_version = "shanghai"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localchain = "${LOCALCHAIN_URL}"
basechain = "${BASE_URL}"
kaiatestnet = "${KAIA_TESTNET_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
